name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '11 11 11 * *'

jobs: 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
        
    - name: Setup AWS Creds
      run: |
        aws --version
        (
          sleep .5
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}"
          sleep .5
          echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          sleep .5
          echo "us-east-1"
          sleep .5
          echo "json"
        ) | aws configure
        
        cat ~/.aws/config

    - uses: kenkaprielian/terraform_state_artifact@main
      with:
        encryptionkey: ${{ secrets.PASSPHRASE }}
        destroy: true


        
        
